# Site settings
title: Hi I'm Tien
email: tiennguyenkhac1702@gmail.com
description: >
  Tien's awesome website, and ordinary yet
  awesome bloke who love to write software
baseurl: ""
url: "http://tien.github.io"
logo: /assets/images/avatar.png
linkedin_username: tien
github_username: tien

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

# Other settings
timezone: Pacific/Auckland

plugins:
  - jekyll-seo-tag
