# Site settings
title: Hi I'm Tiến
author: Tiến Nguyễn Khắc
email: tien.nguyenkhac@icloud.com
description: Tien's awesome website
baseurl: ""
url: "https://tien.zone"
logo: /assets/images/avatar.svg
linkedin:
  username: tien
  url: https://www.linkedin.com/in/tien/
github:
  username: tien
  url: https://github.com/tien

# This is used by the Jekyll SEO plugin
social:
  name: Tiến Nguyễn Khắc
  links:
    - https://www.linkedin.com/in/tien/
    - https://github.com/tien

# Other settings
timezone: Pacific/Auckland

# Front matter default settings
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/avatar.svg

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
