# Site settings
title: Hi I'm Tien
author: Tien Nguyen Khac
email: tiennguyenkhac1702@gmail.com
description: >
  Tien's awesome website, an ordinary yet
  awesome bloke who love to write softwares
baseurl: ""
url: "https://tien.github.io"
logo: /assets/images/avatar.png
linkedin_username: tien
github_username: tien
social:
  name: Tien Nguyen Khac
  links:
    - https://www.linkedin.com/in/tien/
    - https://github.com/tien

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

# Other settings
timezone: Pacific/Auckland
google_site_verification: 1AsH8ct9TgDckOx8UX5LpSe0DkxLIBlGkb3EsKXWH7k

# Front matter default settings
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/avatar.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
