# Site settings
title: Hi I'm Tien
author: Tien Nguyen Khac
email: tiennguyenkhac1702@gmail.com
description: >
  Tien's awesome website, an ordinary yet
  awesome bloke who loves to write software
baseurl: ""
url: "https://tien.github.io"
logo: /assets/images/avatar.png
linkedin:
  username: tien
  url: https://www.linkedin.com/in/tien/
github:
  username: tien
  url: https://github.com/tien

# This is used by the Jekyll SEO plugin
social:
  name: Tien Nguyen Khac
  links:
    - https://www.linkedin.com/in/tien/
    - https://github.com/tien

# Other settings
timezone: Pacific/Auckland
google_site_verification: 1AsH8ct9TgDckOx8UX5LpSe0DkxLIBlGkb3EsKXWH7k
jekyll_analytics:
  GoogleAnalytics:
    id: UA-139436381-1

# Front matter default settings
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/avatar.png

plugins:
  - jekyll-analytics
  - jekyll-seo-tag
  - jekyll-sitemap
